export const whatsappNumber = "628990851133";

export const categories = ["Semua", "City Car", "MPV", "SUV", "Commercial"];
export const rimOptions = ["Semua Ring", "R13", "R14", "R15", "R16", "R17", "R18"];

export const tireProducts = [
  {
    id: 1,
    name: "Dunlop SP Touring R1",
    brand: "Dunlop",
    category: "City Car",
    size: "175/65 R14",
    width: "175 mm",
    profile: "65",
    rim: "R14",
    loadIndex: "82",
    speedRating: "T",
    vehicleType: "City Car",
    compatibleCars: "Brio, Agya, Ayla, Yaris, Jazz",
    character: "Nyaman untuk harian, irit, dan stabil di jalan perkotaan.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart1.webp",
    price: 545000,
    stock: "Ready",
    badge: "Hemat",
    note: "Pilihan aman untuk mobil kecil harian dan pemakaian dalam kota."
  },
  {
    id: 2,
    name: "Bridgestone Techno",
    brand: "Bridgestone",
    category: "MPV",
    size: "185/65 R15",
    width: "185 mm",
    profile: "65",
    rim: "R15",
    loadIndex: "88",
    speedRating: "H",
    vehicleType: "MPV",
    compatibleCars: "Avanza, Xenia, Ertiga, Mobilio, Veloz",
    character: "Empuk, awet, dan cocok untuk keluarga.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart2.webp",
    price: 650000,
    stock: "Ready",
    badge: "Best Seller",
    note: "Ukuran populer untuk MPV keluarga."
  },
  {
    id: 3,
    name: "GT Radial Champiro Eco",
    brand: "GT Radial",
    category: "MPV",
    size: "185/70 R14",
    width: "185 mm",
    profile: "70",
    rim: "R14",
    loadIndex: "88",
    speedRating: "T",
    vehicleType: "MPV",
    compatibleCars: "Avanza lama, Xenia lama, Carry, Gran Max",
    character: "Tapak tahan lama dengan harga ekonomis.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart3",
    price: 575000,
    stock: "Ready",
    badge: "Ekonomis",
    note: "Cocok untuk operasional harian dan kendaraan keluarga."
  },
  {
    id: 4,
    name: "Achilles 122",
    brand: "Achilles",
    category: "City Car",
    size: "195/50 R16",
    width: "195 mm",
    profile: "50",
    rim: "R16",
    loadIndex: "84",
    speedRating: "V",
    vehicleType: "City Car",
    compatibleCars: "Jazz, Yaris, Swift, Baleno",
    character: "Handling lebih responsif dengan tampilan sporty.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart4",
    price: 720000,
    stock: "Ready",
    badge: "Sporty",
    note: "Untuk user yang ingin grip lebih tegas dan tampilan velg lebih padat."
  },
  {
    id: 5,
    name: "Hankook Kinergy Eco2",
    brand: "Hankook",
    category: "MPV",
    size: "185/65 R15",
    width: "185 mm",
    profile: "65",
    rim: "R15",
    loadIndex: "88",
    speedRating: "H",
    vehicleType: "MPV",
    compatibleCars: "Avanza, Xenia, Ertiga, Mobilio",
    character: "Lebih senyap, nyaman, dan efisien untuk perjalanan jauh.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart5",
    price: 690000,
    stock: "Ready",
    badge: "Nyaman",
    note: "Rekomendasi untuk pengguna yang sering keluar kota."
  },
  {
    id: 6,
    name: "Yokohama BluEarth AE50",
    brand: "Yokohama",
    category: "SUV",
    size: "205/55 R16",
    width: "205 mm",
    profile: "55",
    rim: "R16",
    loadIndex: "91",
    speedRating: "V",
    vehicleType: "SUV / Crossover",
    compatibleCars: "HR-V, Civic, Altis, Mazda 3",
    character: "Grip basah bagus, senyap, dan rasa berkendara premium.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart6.jpeg",
    price: 980000,
    stock: "Ready",
    badge: "Premium",
    note: "Cocok untuk mobil harian yang mengutamakan kenyamanan."
  },
  {
    id: 7,
    name: "Michelin Energy XM2+",
    brand: "Michelin",
    category: "MPV",
    size: "185/65 R15",
    width: "185 mm",
    profile: "65",
    rim: "R15",
    loadIndex: "88",
    speedRating: "H",
    vehicleType: "MPV",
    compatibleCars: "Avanza, Xenia, Ertiga, Mobilio",
    character: "Daya cengkeram kuat, awet, dan pengereman stabil.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi resmi sesuai ketentuan produk",
    image: "/images/product_cart2.webp",
    price: 875000,
    stock: "Ready",
    badge: "Rekomendasi",
    note: "Pilihan premium untuk MPV keluarga."
  },
  {
    id: 8,
    name: "Bridgestone Dueler H/T",
    brand: "Bridgestone",
    category: "SUV",
    size: "265/65 R17",
    width: "265 mm",
    profile: "65",
    rim: "R17",
    loadIndex: "112",
    speedRating: "S",
    vehicleType: "SUV",
    compatibleCars: "Fortuner, Pajero Sport, Hilux, Triton",
    character: "Kuat untuk SUV, stabil di tol, tetap nyaman untuk harian.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart1.webp",
    price: 1680000,
    stock: "Ready",
    badge: "SUV Ready",
    note: "Harga belum termasuk pemasangan dan balancing."
  },
  {
    id: 9,
    name: "GT Radial Savero SUV",
    brand: "GT Radial",
    category: "SUV",
    size: "215/65 R16",
    width: "215 mm",
    profile: "65",
    rim: "R16",
    loadIndex: "98",
    speedRating: "H",
    vehicleType: "SUV",
    compatibleCars: "Rush, Terios, HR-V, CR-V generasi awal",
    character: "Tapak kuat untuk aspal dan jalan campuran ringan.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart3",
    price: 920000,
    stock: "Ready",
    badge: "Tangguh",
    note: "Cocok untuk mobil SUV yang sering melewati jalan kurang rata."
  },
  {
    id: 10,
    name: "Dunlop Grandtrek AT",
    brand: "Dunlop",
    category: "Commercial",
    size: "265/60 R18",
    width: "265 mm",
    profile: "60",
    rim: "R18",
    loadIndex: "110",
    speedRating: "H",
    vehicleType: "SUV / Niaga",
    compatibleCars: "Pajero Sport, Fortuner, Triton, Hilux",
    character: "Lebih siap untuk jalan kasar, tetap stabil di aspal.",
    condition: "Baru",
    yearProduction: "2025",
    warranty: "Garansi toko 7 hari",
    image: "/images/product_cart4",
    price: 1950000,
    stock: "Pre-order",
    badge: "All Terrain",
    note: "Hubungi admin untuk cek stok kode produksi terbaru."
  }
];

export const services = [
  {
    title: "Konsultasi Ukuran",
    text: "Bantu cek ukuran ban dari tulisan dinding ban lama, contoh 185/65 R15."
  },
  {
    title: "Pasang & Balancing",
    text: "Pembelian ban bisa sekaligus pemasangan, balancing, dan isi nitrogen."
  },
  {
    title: "Rekomendasi Mobil",
    text: "Admin bantu cocokkan ban dengan Avanza, Brio, Fortuner, Pajero, dan lainnya."
  }
];

export const promos = [
  {
    title: "Gratis Cek Tekanan",
    text: "Setiap konsultasi pembelian ban dapat pengecekan tekanan dan kondisi tapak."
  },
  {
    title: "Paket 4 Ban",
    text: "Tanya admin untuk harga khusus pembelian 4 ban sekaligus."
  },
  {
    title: "Booking Pemasangan",
    text: "Pesan ban dulu via WhatsApp, jadwalkan pemasangan agar tidak antre."
  }
];
